name: Deploy Server

on:

  pull_request:
    # types:
    #   - closed
    branches:
      - main

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build shared
      run: |
          cd app
          cd shared
          mvn clean install -DskipTests

    - name: Build api
      run: |
          cd app
          cd api
          mvn clean install -DskipTests

    - name: Update Dockerfile with env.properties
      run: |
          cd app
          cd api
          echo "DB_REMOTE_URL=jdbc:mysql://bean-bank-coin-db-mysql.cbsozziiwdya.eu-west-1.rds.amazonaws.com:3306/bean_bank_coin_schema" > env.properties
          echo "DB_REMOTE_USER=admin" >> env.properties
          echo "DB_REMOTE_PASSWORD=RXuf4ciWOi?(LhtHjqFU)mXFNKqy" >> env.properties
          sed -i 's|EXPOSE 8080|COPY env.properties env.properties \nEXPOSE 8080|' Dockerfile

    - name: Login to docker hub
      run: |
          cd app
          cd api
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker image
      run: |
          cd app
          cd api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bean-bank-coin .

    - name: Publish image to Docker-hub
      run: |
          cd app
          cd api
          docker push ${{ secrets.DOCKER_USERNAME }}/bean-bank-coin:latest

  deploy:
    needs: build
    # if: github.event.pull_request.merged == true
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bean-bank-coin:latest
      - name: Delete old container
        run: sudo docker rm -f bean-bank-coin-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name bean-bank-coin-container ${{ secrets.DOCKER_USERNAME }}/bean-bank-coin
