name: Flyway Migrations

on:

  pull_request:
    # types:
    #   - closed
    branches:
      - main
  
env:
  FLYWAY_VERSION: 9.16.3
  DB_NAME: bean_bank_coin_db

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flyway
      run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.7.1/flyway /usr/local/bin

    - name: Run Flyway Migrations
      env:
        FLYWAY_URL: jdbc:mysql://bean-bank-coin-db-mysql.cbsozziiwdya.eu-west-1.rds.amazonaws.com:3306/
        FLYWAY_USER: ${{ secrets.DB_BUILD_USERNAME }}
        FLYWAY_PASSWORD: ${{ secrets.DB_BUILD_PASSWORD }}
        FLYWAY_SCHEMAS: bean_bank_coin_schema
      run: |
        flyway repair
        flyway info
        flyway migrate