name: Flyway Migrations

on:

  pull_request:
    # types:
    #   - closed
    branches:
      - main
  
env:
  FLYWAY_VERSION: 9.16.3
  DB_NAME: bean_bank_coin_db

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flyway
      run: |
        wget -qO- https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/${{ env.FLYWAY_VERSION }}/flyway-commandline-${{ env.FLYWAY_VERSION }}-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-${{ env.FLYWAY_VERSION }}/flyway /usr/local/bin 

    - name: Run Flyway Migrations
      env:
        FLYWAY_URL: jdbc:mysql://bean-bank-coin-db-mysql.cbsozziiwdya.eu-west-1.rds.amazonaws.com:3306/bean_bank_coin_db
        FLYWAY_USER: ${{ secrets.DB_BUILD_USERNAME }}
        FLYWAY_PASSWORD: ${{ secrets.DB_BUILD_PASSWORD }}
        FLYWAY_SCHEMAS: bean_bank_coin_schema
      run: |
        # flyway repair
        flyway info
        flyway migrate