name: Flyway Migration

on: 
  pull_request:
    branches:
      - main

jobs:
  migrate:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download Flyway
        run: |
          curl -LJO https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.0.0/flyway-commandline-7.0.0-linux-x64.tar.gz
          tar -xzf flyway-commandline-7.0.0-linux-x64.tar.gz

      - name: Create Flyway Configuration
        run: |
          echo "[flyway]" > flyway.conf
          echo "url = 'jdbc:mysql://${{ secrets.DB_BUILD_URL }}:3306'" >> flyway.conf
          echo "user = '${{ secrets.DB_BUILD_USERNAME }}'" >> flyway.conf
          echo "password = '${{ secrets.DB_BUILD_PASSWORD }}'" >> flyway.conf
          echo "locations = ['filesystem:./migrations']" >> flyway.conf
          echo "databaseType = 'MySql'" >> flyway.conf
          echo "schemas = ['${{ secrets.DB_NAME }}']" >> flyway.conf

      - name: Run Flyway info
        run: ./flyway-7.0.0/flyway -configFile=flyway.conf info

      - name: Run Flyway migrate
        run: ./flyway-7.0.0/flyway -configFile=flyway.conf migrate
