name: Database Migration

on:
  
  pull_request:
    # types:
    #   - closed
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.1/flyway-commandline-8.5.1-linux-x64.tar.gz | tar xvz
          sudo ln -s $(pwd)/flyway-8.5.1/flyway /usr/local/bin/flyway

      - name: Generate Flyway Configuration
      run: |
        echo "flyway.url=jdbc:mysql://${{ secrets.DB_BUILD_URL }}:3306/${{ secrets.DB_NAME }}" >> ./flyway.conf
        echo "flyway.schemas=${{ secrets.DB_NAME }}" >> ./flyway.conf
        echo "flyway.user=${{ secrets.DB_BUILD_USERNAME }}" >> ./flyway.conf
        echo "flyway.password=${{ secrets.DB_BUILD_PASSWORD }}" >> ./flyway.conf
        echo "flyway.validateMigrationNaming=true" >> ./flyway.conf
        echo "flyway.locations=sql" >> ./flyway.conf

      - name: Run Flyway Migration
        run: flyway -configFiles="./flyway.conf" migrate
